"""smr_g4_jobs data

Revision ID: 130a5b414f99
Revises: d1fb71ee287a
Create Date: 2025-07-10 22:23:45.057724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "130a5b414f99"
down_revision: Union[str, Sequence[str], None] = "d1fb71ee287a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "smr_g4_jobs",
        sa.Column("job_stdout", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "smr_g4_jobs",
        sa.Column("job_stderr", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("smr_g4_jobs", "job_stderr")
    op.drop_column("smr_g4_jobs", "job_stdout")
    # ### end Alembic commands ###
