"""smr_g4_jobs is_processing

Revision ID: 377d05734ad4
Revises: 6f9cd02fe235
Create Date: 2025-07-11 11:13:11.937879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377d05734ad4'
down_revision: Union[str, Sequence[str], None] = '6f9cd02fe235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smr_g4_jobs', sa.Column('is_processing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smr_g4_jobs', 'is_processing')
    # ### end Alembic commands ###
