"""smr_g4_jobs data 2

Revision ID: 6f9cd02fe235
Revises: 130a5b414f99
Create Date: 2025-07-10 23:13:31.824614

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f9cd02fe235"
down_revision: Union[str, Sequence[str], None] = "130a5b414f99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "smr_g4_jobs", sa.Column("job_output", postgresql.BYTEA(), nullable=True)
    )
    op.drop_column("smr_g4_jobs", "job_stderr")
    op.drop_column("smr_g4_jobs", "job_stdout")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "smr_g4_jobs",
        sa.Column(
            "job_stdout",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "smr_g4_jobs",
        sa.Column(
            "job_stderr",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("smr_g4_jobs", "job_output")
    # ### end Alembic commands ###
